# Generated by Django 5.0.14 on 2026-06-08 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255, verbose_name='Título')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor')),
                ('categoria', models.CharField(choices=[('alimentacao', 'Alimentação'), ('transporte', 'Transporte'), ('lazer', 'Lazer'), ('saude', 'Saúde'), ('outros', 'Outros')], max_length=20, verbose_name='Categoria')),
                ('data', models.DateField(verbose_name='Data')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Despesa',
                'verbose_name_plural': 'Despesas',
                'ordering': ['-data', '-id'],
            },
        ),
    ]
