# Generated by Django 5.0.14 on 2026-07-01 17:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_expense_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do Banco')),
                ('cor', models.CharField(choices=[('#820ad1', 'Nubank (Roxo)'), ('#ee7d00', 'Inter (Laranja)'), ('#003399', 'Itaú (Azul)'), ('#cc2229', 'Bradesco (Vermelho)'), ('#fff200', 'Banco do Brasil (Amarelo)'), ('#e3120b', 'Santander (Vermelho)'), ('#00a650', 'Sicredi (Verde)'), ('#004b87', 'Caixa (Azul)'), ('#21a038', 'PagBank (Verde)'), ('#1a1a2e', 'C6 Bank (Preto)'), ('#ff4500', 'Original (Laranja)'), ('#6b7280', 'Outro (Cinza)')], default='#6b7280', max_length=7, verbose_name='Cor')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='banks', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Banco',
                'verbose_name_plural': 'Bancos',
                'ordering': ['nome'],
                'unique_together': {('user', 'nome')},
            },
        ),
        migrations.AddField(
            model_name='expense',
            name='banco',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='expenses.bank', verbose_name='Banco'),
        ),
    ]
