# Generated by Django 5.0.14 on 2026-07-02 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0004_expense_num_parcela_recurringexpense_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='categoria',
            field=models.CharField(choices=[('alimentacao', 'Alimentação'), ('transporte', 'Transporte'), ('lazer', 'Lazer'), ('saude', 'Saúde'), ('aluguel', 'Aluguel'), ('assinaturas', 'Assinaturas'), ('luz', 'Luz'), ('agua', 'Água'), ('internet', 'Internet'), ('produtos', 'Produtos (geral)'), ('roupas', 'Roupas'), ('outros', 'Outros')], max_length=20, verbose_name='Categoria'),
        ),
        migrations.AlterField(
            model_name='recurringexpense',
            name='categoria',
            field=models.CharField(choices=[('alimentacao', 'Alimentação'), ('transporte', 'Transporte'), ('lazer', 'Lazer'), ('saude', 'Saúde'), ('aluguel', 'Aluguel'), ('assinaturas', 'Assinaturas'), ('luz', 'Luz'), ('agua', 'Água'), ('internet', 'Internet'), ('produtos', 'Produtos (geral)'), ('roupas', 'Roupas'), ('outros', 'Outros')], max_length=20, verbose_name='Categoria'),
        ),
    ]
